-- Migration 1: ref_skpd table + 34 SKPD data
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS public.ref_skpd (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  nama_skpd VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.ref_skpd (nama_skpd) VALUES
  ('BKPSDM'),
  ('BADAN KESATUAN BANGSA DAN POLITIK'),
  ('BADAN PENANGGULANGAN BENCANA DAERAH'),
  ('BADAN PENDAPATAN PENGELOLA KEUANGAN DAN ASET DAERAH'),
  ('DINAS ARSIP'),
  ('DINAS PEMUDA OLAHRAGA DAN PARIWISATA'),
  ('DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL'),
  ('DINAS KESEHATAN'),
  ('DINAS KETAHANAN PANGAN'),
  ('DINAS KOMUNIKASI DAN INFORMATIKA'),
  ('DINAS LINGKUNGAN HIDUP'),
  ('DINAS PEKERJAAN UMUM DAN PENATAAN RUANG'),
  ('DINAS PEMBERDAYAAN MASYARAKAT KAMPUNG DAN ADAT'),
  ('DINAS PENGENDALIAN PENDUDUK DAN KB'),
  ('DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU'),
  ('DINAS PENDIDIKAN'),
  ('DINAS PERHUBUNGAN'),
  ('DINAS PERINDUSTRIAN PERDAGANGAN KOPERASI DAN UMKM'),
  ('DINAS PERUMAHAN'),
  ('DINAS PERIKANAN'),
  ('DINAS SOSIAL'),
  ('DINAS TANAMAN PANGAN HORTIKULTURA DAN PETERNAKAN'),
  ('DISTRIK BENUKI'),
  ('DISTRIK MAMBERAMO HILIR'),
  ('DISTRIK MAMBERAMO HULU'),
  ('DISTRIK MAMBERAMO TENGAH'),
  ('DISTRIK MAMBERAMO TENGAH TIMUR'),
  ('DISTRIK ROUFAER'),
  ('DISTRIK SAWAI'),
  ('DISTRIK WAROPEN ATAS'),
  ('INSPEKTORAT DAERAH'),
  ('SATUAN POLISI PAMONG PRAJA'),
  ('SEKRETARIAT DAERAH'),
  ('SEKRETARIAT DPRD')
ON CONFLICT (nama_skpd) DO NOTHING;
